export const phoneDatabase = {
  mobile: {
    910: "MCI (Hamrah Aval) - Nationwide",
    911: "MCI (Hamrah Aval) - Mazandaran, Golestan, Gilan",
    912: "MCI (Hamrah Aval) - Tehran, Alborz, Zanjan, Semnan, Qazvin, Qom",
    913: "MCI (Hamrah Aval) - Isfahan, Yazd, Kerman, Chahar Mahal va Bakhtiari",
    914: "MCI (Hamrah Aval) - East Azerbaijan, West Azerbaijan, Ardabil",
    915: "MCI (Hamrah Aval) - Razavi Khorasan, North Khorasan, South Khorasan, Sistan va Baluchestan",
    916: "MCI (Hamrah Aval) - Khuzestan, Lorestan",
    917: "MCI (Hamrah Aval) - Fars, Bushehr, Hormozgan, Kohgiluyeh va Boyer-Ahmad",
    918: "MCI (Hamrah Aval) - Kurdistan, Ilam, Markazi, Kermanshah, Hamedan",
    919: "MCI (Hamrah Aval) - Nationwide",
    990: "MCI (Hamrah Aval) - Nationwide",
    991: "MCI (Hamrah Aval) - Nationwide",
    992: "MCI (Hamrah Aval) - Nationwide",
    993: "MCI (Hamrah Aval) - Nationwide",
    994: "MCI (Hamrah Aval) - Nationwide",
    920: "Rightel",
    921: "Rightel",
    922: "Rightel",
    923: "Rightel",
    930: "Irancell",
    933: "Irancell",
    935: "Irancell",
    936: "Irancell",
    937: "Irancell",
    938: "Irancell",
    939: "Irancell",
    900: "Irancell",
    901: "Irancell",
    902: "Irancell",
    903: "Irancell",
    904: "Irancell",
    905: "Irancell",
    941: "Irancell",
    998: "Shatel Mobile",
    9999: "Samantel Mobile",
    9991: "Aptel",
    99914: "Azartel",
  },
  landline: {
    41: "Tabriz",
    44: "Urmia",
    45: "Ardabil",
    31: "Isfahan",
    84: "Ilam",
    77: "Bushehr",
    21: "Tehran",
    38: "Shahr-e Kord",
    51: "Mashhad",
    56: "Birjand",
    58: "Bojnurd",
    61: "Ahvaz",
    24: "Zanjan",
    23: "Semnan",
    54: "Zahedan",
    71: "Shiraz",
    26: "Karaj",
    25: "Qom",
    28: "Qazvin",
    87: "Sanandaj",
    34: "Kerman",
    83: "Kermanshah",
    74: "Yasuj",
    17: "Gorgan",
    13: "Rasht",
    66: "Khorramabad",
    11: "Sari",
    86: "Arak",
    76: "Bandar Abbas",
    81: "Hamedan",
    35: "Yazd",
  },
};
